name: "DevOps Agent"
description: "Host your own Azure-DevOps Agent"
version: "1.0.0"
slug: "devops_agent"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  AZP_AGENT_NAME: "HomeAssistant"
  AZP_POOL: "Default"
  AZP_URL: "https://dev.azure.com/<yourOrg>"
  AZP_TOKEN: "Your Access Token"
schema:
  AZP_AGENT_NAME: str
  AZP_POOL: str
  AZP_URL: url
  AZP_TOKEN: str
