name: "DevOps Agent"
description: "Host your own Azure-DevOps Agent"
version: "1.0.0"
slug: "devops_agent"
init: false
arch:
  - aarch64
options:
  agentname: "HomeAssistant"
  pool: "Default"
  organization: "https://dev.azure.com/<yourOrg>"
  token: "<YourAccessToken>"
schema:
  agentname: str
  pool: str
  organization: url
  token: str
