arch:
- aarch64
codenotary: mauwii@outlook.de
description: Host your own Azure-DevOps Agent
image: ghcr.io/mauwii/devops-agent/{arch}
init: false
map:
- config:rw
name: DevOps Agent
options:
  agentname: HomeAssistant
  organization: https://dev.azure.com/<your organization>
  pool: Default
  token: <your personal access token>
schema:
  agentname: str
  organization: url
  pool: str
  token: password
slug: devops-agent
url: https://github.com/Mauwii/HA-DevOps-Agent
version: 3720e0a
