arch:
- aarch64
codenotary: Mauwii@outlook.de
description: Host your own Azure-DevOps Agent
image: ghcr.io/mauwii/ha-devops-agent/{arch}
init: false
map:
- config:rw
name: DevOps-Agent
options:
  agentname: HomeAssistant
  init_commands: []
  install_packages: []
  organization: https://dev.azure.com/<your organization>
  pool: Default
  token: <your personal access token>
schema:
  agentname: str
  init_commands:
  - str
  install_packages:
  - str
  organization: url
  pool: str
  token: password
slug: ha-devops-agent
url: https://github.com/mauwii/ha-devops-agent
version: 949b3e7
